### ISSUE TITLE
Extra feature for other players not listed on the Leaderboard

### ISSUE THREAD

**Issue by UnknownPlayer13** [Mirasaki/dayz-leaderboard-bot#21]
A feature command like this /Leaderboard SPECIFIC_CFTOOLS_PLAYERID that gives all related info from that specific player.
(Kills, Kill Death Ratio, Longest Kill, Playtime, Longest Shot, Deaths and Suicides).

Also a custom timed message that is sent on how to get the CFTOOLS_PLAYERID as im sure not everybody knows how to find it.
Beeing able to set the time or after how many /Leaderboard messages the automatic timed message is sent into the specific discord channel

**Comment by Ariastarcos** [comment]
Good feature request, approved - will be added to the bot with a new release shortly

**Comment by Ariastarcos** [comment]
Using the `/leaderboard` command will have a 20% chance to include footer text stating the following:

> Did you know, you can use /stats <cftools-id> to see detailed information on a player?
You can find someone\'s CFTools id on their CFTools Cloud account page
