### ISSUE TITLE
installed it but cant seam to get bot to work

### ISSUE THREAD

**Issue by Sheepgaming1** [Mirasaki/dayz-leaderboard-bot#46]

**Comment by Sheepgaming1** [comment]
![image](https://user-images.githubusercontent.com/93445489/225483984-073267be-7e4a-40d9-a03f-efd6625e06e0.png)

**Comment by Sheepgaming1** [comment]
have put aip keys ect in but just wont seam to work :/

**Comment by Ariastarcos** [comment]
Step [6.3 of the installation guide](https://github.com/Mirasaki/dayz-leaderboard-bot#installation) - you have to authorize/grant access to your server by navigating to the Grant URL displayed for your CFTools Developer Application

**Comment by Sheepgaming1** [comment]
I think this is now fixed this was my sleepy head
